version: "2.3"
services:
  dns:
    image: alphabet5/dnsmasq:latest
    depends_on:
      vpn:
        condition: service_healthy
    entrypoint: dnsmasq
    command:
      - --conf-file=-
      - --log-facility=-
      - --keep-in-foreground
      - --no-hosts
      - --strict-order
      - --listen-address=0.0.0.0
      - --port=1053
      - --bind-interfaces
      - --resolv-file=/etc/resolv.conf
    healthcheck:
      test: [ "CMD-SHELL", "test `ip -o a show | cut -d ' ' -f 2 | grep tun0 | wc -l` -gt 0 || kill 1" ]
      interval: 11s
      timeout: 2s
    network_mode: "service:vpn"
    restart: "always"