version: "2.3"
services:
  ssh:
    image: docker.io/poyaz/ssh-over-vpn
    depends_on:
      vpn:
        condition: service_healthy
    environment:
      SSH_PORT: 1082
    healthcheck:
      test: [ "CMD-SHELL", "test `ip -o a show | cut -d ' ' -f 2 | grep tun0 | wc -l` -gt 0 || kill 1" ]
      interval: 11s
      timeout: 2s
    restart: "always"
    network_mode: "service:vpn"
    logging:
      driver: ${SSH_LOG_DRIVER:-json-file}
      options:
        max-size: ${SSH_LOG_MAX_SIZE:-2m}
        max-file: ${SSH_LOG_MAX_FILE:-10}
